version: "3.8"

services:
  influxdb:
    image: bitnami/influxdb:1.8.5
    platform: linux/amd64
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8085:8088"
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=k6db
    networks:
      - app-tier
  granafa:
    image: bitnami/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-tier
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    user: root
    ports:
      - "9090:9090"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
